#%RAML 1.0
baseUri: https://anypoint.mulesoft.com/mocking/api/v1/links/f957bced-fc7b-461f-aad6-b0b7cc72695b/ # 
title: mule-helloworld

/test:
   get:        
    responses:
     200:
      body:
       application/json: